datasets:
  raw:
    google:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/google_search_data.csv
      driver_params: {}

    product:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/product_manufacturer_list.csv
      driver_params: {}

    sales:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales_data.csv
      driver_params: {}

    social_media:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/social_media_data.csv
      driver_params: {}

    Theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_list.csv
      driver_params: {}

    Theme_Product_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_product_list.csv
      driver_params: {}

  cleaned:
    google:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/google_search_data.parquet
      driver_params: {}
    product:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/product_manufacturer_list.parquet
      driver_params: {}
    sales:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales_data.parquet
      driver_params: {}
    social_media:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/social_media_data.parquet
      driver_params: {}
    Theme_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/Theme_list.parquet
      driver_params: {}
    Theme_Product_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/Theme_product_list.parquet
      driver_params: {}

  processed:
    sales_data_processed:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales_data_processed.parquet
      driver_params: {}
    social_media_data_processed:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/social_media_data_processed.parquet
      driver_params: {}
    google_search_data_processed:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/google_search_data_processed.parquet
      driver_params: {}
    sales_social_google_data_processed:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales_social_google_data_processed.parquet
      driver_params: {}
  train:
    features:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/train/features.parquet
      driver_params: {}
    target:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/train/target.parquet
      driver_params: {}
  test:
    features:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/test/features.parquet
      driver_params: {}
    target:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/test/target.parquet
      driver_params: {}
  score:
    output:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/test/sales/scored_output.parquet
      driver_params:
        save:
          index: False